services:
  mongodb:
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

networks:
  app_network:
    driver: bridge
    
volumes:
  mongo_data:
    driver: local
