name: Zip latest push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'mafiabot.zip'
        exclusions: '*.git* /*.github/*'
    - uses: ncipollo/release-action@v1
        with:
          artifacts: "mafiabot.zip"
          token: ${{ secrets.RELEASE_TOKEN }}